### ISSUE TITLE
sources of entropy / letters

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#1]
for the 'letter' NFT we want some source of randomness. using a real [VRF](https://docs.chain.link/docs/chainlink-vrf/) would be expensive and complex, esp for a hackathon

some other ideas

for each mint there are some special variables available that would give us a different result each mint:
- use the senders wallet address
- latest ETH block
- current gas price
- timestamp of TX?

while a hostile miner maybe able to fake some of these, a fractional change in say gas price for the tx

https://docs.soliditylang.org/en/v0.8.7/units-and-global-variables.html#block-and-transaction-properties

if the minting TX has some other parameters such as a generated TX id, that would also give us more fields to work with.

https://www.trustology.io/insights-events/decoding-an-ethereum-transaction-its-no-secret-its-just-smart

cc @tomosaigon @keepRunning

**Comment by tomosaigon** [comment]
blockhash of blocknumber-1
