### ISSUE TITLE
No logo

### ISSUE THREAD

**Issue by tomosaigon** [GraphemeNFT/rarible-scaffold#16]
Project needs a logo.

It would be rational to use the grapheme generator and word editor itself to make a logo.

**Comment by dcsan** [comment]
yep. i added that original one you sent as the team icon!

**Comment by tomosaigon** [comment]
![image](https://user-images.githubusercontent.com/1016509/131068852-81069e3b-65e8-49c5-92a8-bfdbebbcb594.png)
