### ISSUE TITLE
Some letters will never be generated

### ISSUE THREAD

**Issue by tomosaigon** [GraphemeNFT/rarible-scaffold#17]
Grapheme generator needs to be tweaked to generate letters besides Os and Ps and Bs.

**Comment by tomosaigon** [comment]
Tweak rendering algo to create more variety of glyphs with skipping strokes and diagonal strokes: c56168d8084499f6274b5611f0b45f1b5bdd8025

**Comment by tomosaigon** [comment]
- Z
- H
- T
-

**Comment by dcsan** [comment]
super rare lol!

**Comment by tomosaigon** [comment]
We can return to the "art" after the hackathon when we are free to spend time tweaking the algorithm.
