### ISSUE TITLE
Updates to grapheme.js algorithm breaks rendering of existing DNA

### ISSUE THREAD

**Issue by tomosaigon** [GraphemeNFT/rarible-scaffold#18]
The rendering algo is still being tweaked but this potentially breaks old DNA.

We could have a versioning system.

We could pin grapheme.js on ipfs and store the cid as a version for a contract.

**Comment by dcsan** [comment]
concern for a hackathon? has DNA changed hugely? it's always going to be a sequence.

Can we lock it as the 32bytes of hex that we have now?

**Comment by tomosaigon** [comment]
Something to be aware of internally but the solutions can simply be mentioned in the slide deck without implementing for the hackathon.
