### ISSUE TITLE
Your Collectibles list should fetch DNA per token

### ISSUE THREAD

**Issue by tomosaigon** [GraphemeNFT/rarible-scaffold#19]
Currently using fake data for each real minted token.

**Comment by dcsan** [comment]
implemented `getDNA` method and this is working on the `letters` page with useEffect to call contract for each token

![image](https://user-images.githubusercontent.com/514002/131203638-785c32c3-425a-4fdc-be11-05705e1dd18f.png)

**Comment by tomosaigon** [comment]
Looks good
