### ISSUE TITLE
show on opensea

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#2]
register
https://testnets.opensea.io/get-listed/step-two

but they don't support ropsten?

![image](https://user-images.githubusercontent.com/514002/130556465-eba93b61-5360-4e97-9f3d-57a66b62d5b2.png)

**Comment by dcsan** [comment]
can we do this with a local running chain only, or need to switch to using ropsten ?

**Comment by tomosaigon** [comment]
For testing/demo we need Rarible's (sponsor's) contracts if anything. So it doesn't matter what testnet Opensea is on. 

Show on Opensea post-hackathon.
