### ISSUE TITLE
Token view should let original minter Claim the Letter

### ISSUE THREAD

**Issue by tomosaigon** [GraphemeNFT/rarible-scaffold#21]
Along with showing current Claim status, have something for users to Claim those they like.

**Comment by tomosaigon** [comment]
UI is implemented: 53149997307f1d936bf80dfe49f3ad99508d478f

**Comment by tomosaigon** [comment]
WordTool has a "Cast Word" button that does all the work except writing to the contract.

**Comment by dcsan** [comment]
does this create a capture we can use as an IPFS mint?
these are the ones we really want to show off on rarible etc., so the metadata is important.

![image](https://user-images.githubusercontent.com/514002/131230709-992512ee-6840-4639-b6be-67db534e501e.png)

**Comment by tomosaigon** [comment]
Mint button is on Letters
