### ISSUE TITLE
Roll/Mint should just go to connected address without manual user input

### ISSUE THREAD

**Issue by tomosaigon** [GraphemeNFT/rarible-scaffold#24]
The original Mint component takes Recip Address and ipfs hash.

**Comment by dcsan** [comment]
removed the IPFS field

but left original way to mint below.

![image](https://user-images.githubusercontent.com/514002/131203578-60c0b29b-3f54-46c1-ae37-b3c260070648.png)

**Comment by tomosaigon** [comment]
"rollToMint" works as expected (without requiring input).
