### ISSUE TITLE
bug on generating IPFS address

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#26]
rollToMint causes these output errors

![image](https://user-images.githubusercontent.com/514002/131093705-5b2d616c-aa6a-4487-869d-e10cb6fc9695.png)

plus chain errors

```
eth_accounts (2)
eth_call
  Contract call:       YourCollectible#tokenURI
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9

eth_accounts (2)
eth_call
  Contract call:       YourCollectible#tokenOfOwnerByIndex
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9

eth_accounts (2)
eth_call
  Contract call:       YourCollectible#tokenURI
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9

eth_accounts (2)
eth_call
  Contract call:       YourCollectible#tokenOfOwnerByIndex
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9
```

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/131093873-fd545d00-c6ba-45c1-b617-39b098836fd3.png)

anyway added a button to call that on webUI, but it doesn't pass an IPFS hash.

**Comment by tomosaigon** [comment]
rollToMint should not be passed an ipfs hash.

It's not needed until Claim.

**Comment by dcsan** [comment]
yeah it's not being passed an IPFS hash. 

https://github.com/GraphemeNFT/rarible-scaffold/blob/rarible-local/packages/react-app/src/components/Mint.jsx#L55

i just left the field there as 'Mint' still takes it.

but not sure where that code above is triggered from, possibly some hook?

so rollToMint doesn't seem to add anything to your wallet, mint does, perhaps its failing due to that IPFS glitch

**Comment by dcsan** [comment]
rendering was broken when IPFS hash didn't exist.
