### ISSUE TITLE
integrate ASCII render widget on letters page

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#34]
currently:

- 'your collectibles' page has UI built, but dummy data
a bit of messy code all in App.jsx

- letters page does contract querying but no UI 
also it's more modularly built

need to decide which page to extend and merge these two features, i would go with letters.

**Comment by dcsan** [comment]
@tomosaigon thoughts?

**Comment by tomosaigon** [comment]
Done
