### ISSUE TITLE
stability

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#36]
If i leave the app open it will crash ~ 5 minutes?

not sure if we can at least trap these errors but fairly deep in network chatter. 

```
Unhandled Rejection (Error): missing response (requestBody="{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xa478c2975ab1ea89e8196811f51a7b7ade33eb11\",\"data\":\"0x0902f1ac\"},\"latest\"],\"id\":142,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={}, url="https://mainnet.infura.io/v3/460f40a260564ac4a4f4b3fffb032dad", code=SERVER_ERROR, version=web/5.3.0)
Logger.makeError
/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/src.ts/index.ts:213
Logger.throwError
/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/src.ts/index.ts:225
(anonymous function)
/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/src.ts/index.ts:234
rejected
http://localhost:3000/static/js/0.chunk.js:98920:32
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
```

![image](https://user-images.githubusercontent.com/514002/131204099-33ee927c-b7f8-4717-b9d2-ab1e0bf18288.png)

**Comment by keepRunning** [comment]
This might be throttling on the infura end since we have not configured our infura keys.
 We can't rely on public ones. We have to use personal infura project key for this.

**Comment by tomosaigon** [comment]
Let's reassess after deploying to Ropsten, it'll either get worse or we realize there's bigger problems. I think updating on every block is the source of a big problem.

**Comment by dcsan** [comment]
this has been more stable recently.

wouldn't it also be pretty easy to get our own free account / keys?

**Comment by dcsan** [comment]
https://github.com/austintgriffith/scaffold-eth/issues/352

**Comment by dcsan** [comment]
still a problem. but probably a deeper issue than we have time to fix this hackathon.
