### ISSUE TITLE
view other's letters / words ?

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#37]
## letters
do we need a page to view other people's letters?
pending adding a "borrow" feature.

how would this be implemented?
if we don't use rarible indexer...

make the contract itself store all it's users in a second array? 
does this incur much gas cost?

then we'd need another way to iterate that list, and retrieve tokens for the NON-current user.
ie by ... wallet address, not by index ?

## words
would need similar, eventually.

also how would these final creations be viewed on other places like opensea?

**Comment by dcsan** [comment]
@tomosaigon @keepRunning any ideas on best way to do this?

**Comment by tomosaigon** [comment]
Words aren't needed as far as utility goes, as nothing depends on Words.

Letters - the idea was always to have the function to rent someone else's Letter. Then Sri suggested using Royalty functionality from Rarible. At this point we haven't made anything work around Royalties. 

Punt this until there's remaining time to add this feature.
