### ISSUE TITLE
minting requires IPFS hash

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#4]
![image](https://user-images.githubusercontent.com/514002/130560406-52ce2100-6718-4dcb-bc87-0c547cb2b7b0.png)

current mintUI requires an IPFS hash, but script doesn't generate one til just before we mint?

should we create a temp IPFS hash to put in the web UI?
why does the web UI even force you to specify it?

```
  console.log("Uploading buffalo...")
  const uploaded = await ipfs.add(JSON.stringify(buffalo))

  console.log("Minting buffalo with IPFS hash (" + uploaded.path + ")")
  await yourCollectible.mintItem(toAddress, uploaded.path, { gasLimit: 400000 })
```

**Comment by tomosaigon** [comment]
I think our workflow will be different.

We need to call a "mint" function in the contract which will mint (create) the token and set the random hex value. After that, the metadata.json can be generated using that value, and only then can the metadata.json's ipfs cid be saved as tokenURI.

**Comment by dcsan** [comment]
yep agreed. the above form is kinda weird IMHO. its as if you want to just make a mint and you already know the URL of some JPEG or something, not our use case at all. so like you say we will:

- roll and get hash value back from contract
- create metadata json including hash
- upload to IPFS
- get IPFS hash (address)
- add hash to JSON
- mint with IPFS hash

and we don't need to ask the user for anything
