### ISSUE TITLE
claim letter

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#42]
ok basics working for this but i just return dummy data odd/even for `isClaimed`

when doing the `claimToken` method i think we might need:

- tokenId
- ipfs address

what about:
- sender? (or is this just msg.sender) - ie a way that people other than the person who minted can claim it.
- name? if we let people "name" their letters. this is in the UI now, but I'm not sure it adds much? @tomosaigon 

on 'claiming' we should mint to: and take money from the user right??
that's the main point of NFTs lol

![image](https://user-images.githubusercontent.com/514002/131207231-b0d8e3e5-b14c-4970-bd72-049409278ecd.png)

**Comment by dcsan** [comment]
@keepRunning 
now I'm just waiting for 

- `claimToken`
- `getInfo` (including all token info like claimed status, maybe owner in case we have a gallery page with everyone's tokens?)

**Comment by tomosaigon** [comment]
![image](https://user-images.githubusercontent.com/1016509/131207356-92509e1d-068b-4113-9a04-0925729e35cb.png)

"claim" function will set tokenURI to the passed in uri (an ipfs cid)

**Comment by tomosaigon** [comment]
"name" is a field in the metadata standard and is presumably used by NFT marketplaces

**Comment by dcsan** [comment]
yeah those params are there now in the fn
but was wondering if we need others...

**Comment by tomosaigon** [comment]
Name is nice to have, others might also be nice (e.g. a better description) but nothing seems to be a deal breaker for the rest of the hackathon.
