### ISSUE TITLE
perishable letters / lifetime?

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#43]
if someone doesn't claim a letter should we have a type of 'lifetime' on it? ie it goes back into the pool and you lose the chance to claim it after 24 hours?

we can implement that in the UI too.

is there a way to give a user a refund? not sure we need to do that, but it's an idea... let them "burn" tokens to get half their money back, monopoly mortgage style

**Comment by tomosaigon** [comment]
Blue Sky
