### ISSUE TITLE
how to get back IPFS data?

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#46]
![image](https://user-images.githubusercontent.com/514002/131211819-7956382f-77b0-4b90-8981-166ab33c89bf.png)

the metedata exists in IPFS - how can we retrieve that?
eg to get the image URL and especially the `name` property

**Comment by keepRunning** [comment]
get the tokenUri from contract using getTokenInfo() or tokenURI() methods

then call similar code
const jsonManifestBuffer = await getFromIPFS(ipfsHash);
jsonManifest = JSON.parse(jsonManifestBuffer.toString());

**Comment by tomosaigon** [comment]
See the getFromIPFS helper function in App.jsx.
