### ISSUE TITLE
graphemes are updating - cos of PRNG inside grapheme.js ?

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#48]
I'm not changing anything but the image data is updating on UI refresh.

I think cos there's still some random number entropy stuff inside the `grapheme` renderer.
not sure if its good for me to dig into that code...

btw I'm just taking a slice off the numbers - first 12 hex digits to use to render with.

```
            graphemeContract.getInfo(tokenId)
                .then((infoRes) => {
                    // returns an array of dna, isClaimed
                    const [dnaObj, isClaimed] = infoRes
                    // console.log('info', infoRes)
                    const hex = dnaObj.toHexString()
                    setHex(hex)
                    const firstHex = hex.slice(0, 12)
                    const num = parseInt(firstHex, 16)
                    const digits = num.toString().split('')
                    const dna = digits.map(digit => parseInt(digit))

                    // const num = dnaObj.toNumber() / 1e12
                    setItemDna(dna) // last 6 digits e12-e18
                    setClaimed(isClaimed)
                    console.log({ isClaimed, hex, num, dna })
                })
```

![image](https://user-images.githubusercontent.com/514002/131213402-6c2cc88e-facf-4898-800e-16898ab3b474.png)

![image](https://user-images.githubusercontent.com/514002/131213406-876dcd9b-b210-496f-9fa2-165be30b8726.png)

**Comment by tomosaigon** [comment]
There's no PRNG, the generator cycles through the token's DNA passed in. 

You are probably changing the value and calling the render code with a different value.

**Comment by dcsan** [comment]
> There's no PRNG, the generator cycles through the token's DNA passed in.

is it expecting a set number of characters? I'm passing 12 nums now eg `176661098459`

it's triggered by the transfer events coming in

put the token in now lets see:

![image](https://user-images.githubusercontent.com/514002/131227962-3d857c7f-99d6-4976-8f43-4fb831939235.png)

![image](https://user-images.githubusercontent.com/514002/131227988-d96b2e11-1e53-4a79-a87e-8ae8e2680e8d.png)

**Comment by dcsan** [comment]
so the top left one, token is consistent at `176661098459`
but the images are changing.

![image](https://user-images.githubusercontent.com/514002/131228026-4270db91-e5d5-4884-a57a-e46f3d664efd.png)

![image](https://user-images.githubusercontent.com/514002/131228029-a976a9c7-f7c3-4449-82fe-a51ef3fe4e8c.png)

**Comment by dcsan** [comment]
if it's _rotating through_ what's the goal of that? or you mean it just iterates over the data passed in?

**Comment by dcsan** [comment]
ok i think perhaps tokenId and metadata are getting shifted somehow

**Comment by dcsan** [comment]
ok finally figured this out. the code inside grapheme was mutating the passed in react state variables. so each render was indeed `rot`ating the dna, causing the letter to change on each redraw.

fix

```
        const cloneDna = [...itemSig.dna]
        renderLetter(grid, makeRng(cloneDna));
```
