### ISSUE TITLE
editor should use real letters, not the fake letters

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#57]
that means extracting the guts of this page similar to the letters page?
then injecting the real letters

and allowing user to move around
then `Cast` button should connect to the actual contract.

![image](https://user-images.githubusercontent.com/514002/131230722-29a8c983-bc81-457d-9bf3-94abbd29df89.png)

**Comment by dcsan** [comment]
@tomosaigon whats the state of any IPFS metadata created here?

**Comment by tomosaigon** [comment]
Done
