### ISSUE TITLE
switch to a canvas rendered glyph

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#58]
it's hard to control the layout of the ascii version, or to scale it to fit into a set area.

if we used canvas version we could scale it more easily.

![image](https://user-images.githubusercontent.com/514002/131233712-eb24382d-0680-41e3-8375-3c31775a252d.png)

**Comment by dcsan** [comment]
can i get to the canvas renderer easily?

**Comment by dcsan** [comment]
seems this is the code, but not sure what these `split2bits` etc are for. 

this 'function' doesn't take any params so it depends on external state.


```
  useEffect(() => {
    if (!canvasRef.current) {
      return;
    }
    const split2bits = (bits) => [16 * 5 * (bits & 0b110000) >> 4, 16 * 5 * (bits & 0b1100) >> 2, 16 * 5 * (bits & 0b11)];
    const ary2rgba = (ary) => 'rgba(' + ary.join(',') + ', 1)';
    const fontSize = 10;

    let ctx = canvasRef.current.getContext('2d');
    //let ctx = canvasRef.current.getContext('2d' /* weird alias effect: , { alpha: false } */);
    console.log('-------------------------');
    ctx.clearRect(0, 0, canvasWidth, canvasHeight);
    //ctx.scale(0.5, 0.5);
    let gradient1 = ctx.createLinearGradient(0, 0, canvasWidth, canvasHeight);

```

could i get away with just this part for a b/white version?

```
    grid.forEach((row, idx) => {
      ctx.strokeText(row.join(''), 0, fontSize + idx * fontSize)
    });

```

ref #59

**Comment by dcsan** [comment]
ideally i want a function to pass in a canvas, dna, and have it draw into that context. maybe more difficult in react world too with refs etc...

**Comment by tomosaigon** [comment]
"could i get away with just this part for a b/white version?" - yes, for a single letter all that new gradient code doesn't apply

**Comment by dcsan** [comment]
pretty much done.

**Comment by tomosaigon** [comment]
Done
