### ISSUE TITLE
fix hardwired contracts in source

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#6]
even for local dev, it seems the contracts are referred to in multiple places in the source AND they will be different for each dev.

at a minimum we need to ignore those files
ideally move all these config vars to a single place.

also, its a pain to have to manually edit places in source each time contract is deployed

maybe this works better when we have a shared remote blockchain and contract?
but even then not sure how it would work with ssh keys etc to update.

**Comment by dcsan** [comment]
nb c50b7556a195eafea76e62307847735244e5ddc6

**Comment by tomosaigon** [comment]
this sucks but we only have to deal with it for another day or so

**Comment by dcsan** [comment]
i have a `make update` cmd that also calls publish so the manual editing of files isn't needed.
however some of those files aren't ignored so after each pull other devs need to compile and update for local dev.
