### ISSUE TITLE
rollToMint: Get connected wallet address and set as minting to 

### ISSUE THREAD

**Issue by tomosaigon** [GraphemeNFT/rarible-scaffold#61]

**Comment by dcsan** [comment]
this is basically working?

i note it does have a 0 price, do we need to call setMintPrice somewhere @keepRunning 

![image](https://user-images.githubusercontent.com/514002/131237616-1a986ac7-a163-4da3-9b7d-c35d9606146d.png)

**Comment by dcsan** [comment]
oh you mean prefill users wallet, OK!

**Comment by dcsan** [comment]
let me try this as i want to see about making wallet more golbally availalbe in a shared state

**Comment by dcsan** [comment]
added Zustand
