### ISSUE TITLE
Unique name for Collectible Token(s)

### ISSUE THREAD

**Issue by tomosaigon** [GraphemeNFT/rarible-scaffold#8]
The default in contracts from the Rarible branch is set like this: ERC721("YourCollectible", "YCB") 

Propose changing to ERC721("Grapheme", "PHEME").

That's for a "Letter". Then for the "Word", how about ERC721("GraphemeCombo", "PHEMEBO").

**Comment by dcsan** [comment]
`("Grapheme", "PHEME").` sure

why `PHEMEBO` ?

**Comment by tomosaigon** [comment]
I was thinking:

graPHEME -> PHEME
graPHEME comBO -> PHEMEBO

Just the last syllable of each word.

**Comment by keepRunning** [comment]
Do we need seperate contracts for Letter and Word? There will be only one of each anyway.

**Comment by dcsan** [comment]
word needs to contain links to a bunch of letters, would seem cleaner to separate them?

or are you thinking of putting multiple features into one contract and the client just uses different functions on diff pages?

**Comment by keepRunning** [comment]
am thinking of the latter. Unless its gets too messy with naming, keeping it in one contract is better. 
Also, helps in listing a single contract for marketplaces.

**Comment by tomosaigon** [comment]
Looks like it's 1 contract that contains both Letters and Words. Maybe not ideal but if it works... 

I think it should be 2 contracts, thus having 2 names, "PHEME" and something like "PHEMEBO" or "WORD".
