### ISSUE TITLE
change render preview based on type

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#82]
the 'word' types should pull their image from ipfs thumbnail, not use a render like the letters

now the words are using a generic / default DNA string?
maybe we could just change that in the meantime to say "WORD" or something...

![image](https://user-images.githubusercontent.com/514002/131268700-0ed2430b-2f35-406b-af23-58ebbb9384c6.png)

**Comment by dcsan** [comment]
also the 'word' doesn't match

AND we should not show words on the 'editor' page, just letters... (tho they do look nice)

![image](https://user-images.githubusercontent.com/514002/131268729-4f357764-bb9f-4bd9-beb9-c0ee7b7cdcb2.png)

**Comment by dcsan** [comment]
#50

**Comment by tomosaigon** [comment]
No need
